version: '3.8'

services:
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: loc-mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - loc-mailpit-net

networks:
  loc-mailpit-net:
    driver: bridge
